# JLab Common Environment (CE) docker image to run GEMC in interactive mode
#
# This Dockerfile is inspired by the jlabce container developed by D. Lawrence and M. Ungaro:
#
# https://gitlab.com/ESC/containers/tree/master/Docker/JLEIC/jlabce
#
# The xstart scripts start the servers
#
#
# Instructions:
#
#--------------------------------------------------------------------------
#
# Remember to find/replace the gemcbatch version to the latest one and match
# it with the gemcinteractive version
#
# To build and push the container:
#
#  docker build -f Dockerfile-gemcinteractive -t gemcinteractive:2.7 .
#
#  docker tag gemcinteractive:2.7 jeffersonlab/gemcinteractive:2.7
#
#  docker push jeffersonlab/gemcinteractive:2.7
#
#--------------------------------------------------------------------------
#
# To run in batch mode:
#
#  docker run -it --rm jeffersonlab/gemcinteractive:2.7 bash
#
# To use vnc or noVNC:
#
#   docker run -it --rm -p 6080:6080 -p 5901:5901 jeffersonlab/gemcinteractive:2.7
#
# On a mac, if you allow access from localhost with:
#
#  1. Activate the option ‘Allow connections from network clients’ in XQuartz settings (Restart XQuartz (to activate the setting)
#  2. xhost +127.0.0.1
#
# Then you can run docker and use the local X server with:
#
#  docker run -it --rm -e DISPLAY=docker.for.mac.localhost:0 jeffersonlab/gemcinteractive:2.7 bash
#
#--------------------------------------------------------------------------

FROM jeffersonlab/gemcbatch:2.7
LABEL maintainer "Maurizio Ungaro <ungaro@jlab.org>"

#--------------------------------------------------------------------------
# Add graphics support
# mailcap needed for the novnc icons
RUN yum install -y \
	tigervnc-server \
	xfce4-session \
	xfce4-panel \
	xfce4-terminal \
	xfwm4 \
	mailcap \
	ghostscript-fonts \
	net-tools \
	glx-utils \
	python-websockify \
	xterm \
	nedit \
	git \
	&& yum clean all \
	&& rm -rf /var/cache/yum \
	&& git clone https://github.com/kanaka/noVNC.git /opt/noVNC \
	&& cd /opt/noVNC \
	&& ln -s vnc.html index.html \
	&& mkdir -p /container/utilities


# These define an alias and a script for easily starting up the
# servers from either bash or tcsh.
COPY scripts/xstart_alias.sh  /etc/profile.d
COPY scripts/xstart_alias.csh /etc/profile.d
COPY scripts/xstart.sh  /container/utilities
COPY scripts/xstart.csh /container/utilities
COPY scripts/xstop /usr/bin
ADD  dot_config /root/.config

WORKDIR $JLAB_ROOT/work
CMD bash /container/utilities/xstart.sh && sleep infinity
