#
# TODO:
# - add gcard to each detector in the clas12tag distribution
#
# JLab Common Environment (CE) docker image to run GEMC in batch mode
#
# This Dockerfile is inspired by the jlabce container developed by D. Lawrence and M. Ungaro:
#
# https://gitlab.com/ESC/containers/tree/master/Docker/JLEIC/jlabce
#
# Instructions:
#
#--------------------------------------------------------------------------
#
# Remember to find/replace the JLAB_VERSION and the gemc version
# with the correct ones. Run the geo packager with the correct geometry tag.
#
# To build and push the container:
#
#  docker build -f Dockerfile-gemcbatch -t gemcbatch:2.7 .
#
#  docker tag gemcbatch:2.7 jeffersonlab/gemcbatch:2.7
#
#  docker push jeffersonlab/gemcbatch:2.7
#
#--------------------------------------------------------------------------
#
# To run in batch mode:
#
#  docker run -it --rm jeffersonlab/gemcbatch:2.7 bash
#
#--------------------------------------------------------------------------

FROM centos:7.5.1804
LABEL maintainer "Maurizio Ungaro <ungaro@jlab.org>"

#--------------------------------------------------------------------------
# JLab CE (Common Environment)
#
# Add enterprise linux repositories
RUN yum install -y epel-release
#
RUN yum install -y \
	cmake3 \
	make \
	scons \
	gcc-c++ \
	mysql \
	mysql-devel \
	python-devel \
	libX11-devel \
	mesa-libGLU-devel \
	libXt-devel \
	libXmu-devel \
	libXrender-devel \
	libXpm-devel \
	libXft-devel \
	expat-devel \
	bzip2 \
	qt5-qtbase-devel \
	qt5-linguist \
	wget \
	nano \
	git \
	which \
	tcsh \
	psmisc \
	&& yum clean all \
	&& rm -rf /var/cache/yum \
	&& ln -s /usr/bin/cmake3 /usr/local/bin/cmake

ADD .jlab_software /root

ENV JLAB_ROOT /jlab
ENV JLAB_VERSION 2.3

RUN mkdir -p $JLAB_ROOT/$JLAB_VERSION $JLAB_ROOT/work

WORKDIR $JLAB_ROOT

RUN rm -f ceInstall_$JLAB_VERSION.tar.gz \
	&& wget -c http://www.jlab.org/12gev_phys/packages/sources/ceInstall/ceInstall_$JLAB_VERSION.tar.gz \
	&& ln -s /usr/bin/qmake-qt5 /usr/bin/qmake \
	&& tar -zxpf ceInstall_$JLAB_VERSION.tar.gz --strip-components 1 -C $JLAB_VERSION \
	&& source $JLAB_ROOT/$JLAB_VERSION/ce/jlab.sh \
	&& cd $JLAB_ROOT/$JLAB_VERSION/install \
	&& ./go_clhep \
	&& ./go_xercesc \
	&& ./go_qt \
	&& ./go_geant4 \
	&& ./go_sconsscript \
	&& ./go_evio \
	&& ./go_mysql \
	&& ./go_ccdb \
	&& ./go_mlibrary \
	&& ./go_gemc \
	&& rm -rf $JLAB_SOFTWARE/geant4/*/source \
	&& rm -rf $JLAB_SOFTWARE/xercesc/*/xerces-c-* \
	&& rm -rf $JLAB_SOFTWARE/mlibrary/*/cadmesh* \
	&& ln -s $JLAB_ROOT/$JLAB_VERSION/ce/jlab.sh /etc/profile.d \
	&& ln -s $JLAB_ROOT/$JLAB_VERSION/ce/jlab.csh /etc/profile.d \
	&& cd $JLAB_ROOT/work \
	&& wget -c  http://www.jlab.org/12gev_phys/packages/sources/gemc/geo.tar.gz \
	&& tar -zxpvf geo.tar.gz \
	&& rm geo.tar.gz

WORKDIR $JLAB_ROOT/work

